<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

 /**
     * @ORM\OneToOne(targetEntity="Query", inversedBy="user")
     */
    protected $query;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Hook on pre-update operations
     */
    public function preUpdate()
    {
        $this->lastLogin = clone $this->updatedAt;
        $this->updatedAt = new \DateTime();
    }

    public function getQuery()
    {
        return $this->query;
    }

    public function setQuery(Query $query)
    {
        $this->query = $query;

        return $this;
    }
}
